export const textColors = {
  black: "text-black",
  white: "text-white",
  offBlack: "text-gray-900",
  dark: "text-sky-950",
  darkSecondary: "text-sky-900",
  darkTertiary: "text-sky-800",
  darkAccent: "text-sky-700",
  light: "text-gray-50",
  lightSecondary: "text-gray-100",
  lightTertiary: "text-gray-200",
  lightAccent: "text-gray-300",
  lightMedium: "text-gray-400",
  medium: "text-gray-500",
  extraMedium: "text-gray-600",
  hover: {
    black: "hover:text-black",
    white: "hover:text-white",
    offBlack: "hover:text-gray-900",
    dark: "hover:text-sky-950",
    darkSecondary: "hover:text-sky-900",
    darkTertiary: "hover:text-sky-800",
    darkAccent: "hover:text-sky-700",
    light: "hover:text-gray-50",
    lightSecondary: "hover:text-gray-100",
    lightTertiary: "hover:text-gray-200",
    lightAccent: "hover:text-gray-300",
    lightMedium: "hover:text-gray-400",
    medium: "hover:text-gray-500",
    extraMedium: "hover:text-gray-600",
  },
} as const;
